### ISSUE TITLE
没有phishlang.deb文件

### ISSUE THREAD

**Issue by jiakaxi** [UTA-SPRLab/phishlang#1]
没有phishlang.deb文件呀，是install文件吗？（Step 1: Install the Client-Side Service
步骤1：安装客户端服务
Navigate to the folder containing phishlang.deb.
导航到包含phishlang.deb的文件夹。

Enter the following command in the terminal:
在终端中输入以下命令：

sudo dpkg -i phishlang.deb

OR  或

Double-click on the .deb file and install it.
双击.deb文件并安装它。)

**Comment by SayakSR** [comment]
Updated path for installer.deb in Readme.
